name:                space-station15
version:             0.1.0.0
github:              "Execyte/space-station15"
license:             BSD-3-Clause
author:              "Execyte"
maintainer:          "execute@erisws.com"
copyright:           "2025 Execyte"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Execyte/space-station15#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- vector
- lens
- sdl2
- apecs
- linear
- async
- serialise
- containers
- crypton
- hourglass
- memory
- tls
- x509
- quic
- quic-simple
- network
- aeson
- text
- random
- OpenAL
- OpenGL
- exceptions
- StateVar
- dear-imgui
- unliftio
- stm
- extra
- JuicyPixels

library:
  source-dirs:
  - assets
  - src/shared

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- TypeFamilies
- TypeFamilyDependencies
- BangPatterns
- KindSignatures
- TypeOperators
- DataKinds
- QuasiQuotes
- InstanceSigs
- EmptyCase
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- DisambiguateRecordFields
- DuplicateRecordFields
- RecordWildCards
- TupleSections
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- StandaloneDeriving
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses
- ScopedTypeVariables
- TemplateHaskell
- TypeApplications
- GeneralizedNewtypeDeriving
- OverloadedStrings
- ConstraintKinds
- RankNTypes
- DefaultSignatures
- PatternSynonyms
- ExistentialQuantification
- FunctionalDependencies
- BlockArguments
- ImportQualifiedPost
- GADTs

executables:
  space-station15-client:
    main: Main.hs
    source-dirs:
    - app/client
    - src/client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - space-station15

  space-station15-editor:
    main: Main.hs
    source-dirs:
    - app/editor
    - src/client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - space-station15

  space-station15-server:
    main: Main.hs
    source-dirs:
    - app/server
    - src/server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - space-station15
